steps:
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    on:
      push:
        branches:
          - main
          - next
          - beta-v10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
