steps:
  - name: Semantic Release
    on:
      push:
        branches:
          - 'master'
          - 'next'
          - 'beta-v10'
    uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
